import Head from "next/head";

export default function About() {
    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="h-screen">
                <h1 className="p-32 text-4xl">About us content</h1>
            </div>
        </>
    );
}


