import Head from "next/head";
import Link from "next/link"
import Image from "next/image"
import { AiFillLinkedin } from "react-icons/ai"
import { AiFillTwitterSquare } from "react-icons/ai"
import { AiFillFacebook } from "react-icons/ai"
import { AiFillInstagram } from "react-icons/ai"
import { AiFillYoutube } from "react-icons/ai"

export default function Careers() {
   
  const d = new Date();
  const w = ['Sun', 'Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat'];
  const m = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Sept', 'Oct', 'Nov', 'Dec'];

  const day = w[d.getDay()];
  const month = m[d.getMonth()];
  const date = d.getDate()
  const year = d.getFullYear()
  return (
    <>
      <Head>
        <title>Careers</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className="h-screen mb-10">

        <div className=" h-full absolute inset-0 top-14 bg-light-blue-300 opacity-95 ">
          <Image
            alt="Background Image"
            src="https://res.cloudinary.com/filipe256/image/upload/v1642172209/qraftstore/hero-bg_ytthxj.png"
            layout="fill"
            objectFit="cover"
            quality={100}
          />
        </div>

        <div className="flex flex-col py-44 text-left text-white md:text-center z-10 relative">
          <h1 className="text-center text-4xl md:text-6xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-green-300 to-white mb-8">
            Under Construction
          </h1>
          <div className="flex justify-center items-center space-x-4">
            <article className="text-center bg-black rounded-lg shadow-lg p-5 md:p-14 bg-gradient-to-r from-blue-500">
              <h1 className=" md:text-6xl font-extrabold">{day}</h1>
            </article>
            <article className="bg-black rounded-lg shadow-lg p-5 md:p-14 bg-gradient-to-r from-blue-500">
              <h1 className="md:text-6xl font-extrabold">{date}</h1>
            </article>
            <article className="bg-black rounded-lg shadow-lg p-5 md:p-14 bg-gradient-to-r from-blue-500">
              <h1 className="md:text-6xl font-extrabold">{month}</h1>
            </article>
            <article className="bg-black rounded-lg shadow-lg p-5 md:p-14 bg-gradient-to-r from-blue-500">
              <h1 className="md:text-6xl font-extrabold">{year}</h1>
            </article>
          </div>
          <div className="flex justify-center space-x-4 mt-8">
            <Link href="/dashboard"><a><AiFillLinkedin size={28} /></a></Link>
            <Link href="/dashboard"><a><AiFillTwitterSquare size={28} /></a></Link>
            <Link href="/dashboard"><a><AiFillFacebook size={28} /></a></Link>
            <Link href="/dashboard"><a><AiFillInstagram size={28} /></a></Link>
            <Link href="/dashboard"><a><AiFillYoutube size={28} /></a></Link>
          </div>
        </div>
      </header>
    </>
  );
}



