import Head from "next/head";

export default function Careers(){
    return (
      <>
          <Head>
                <title>Careers</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
        <div className="h-screen">
          <h1 className="p-32 text-4xl">Career content</h1>
        </div>
        </>
    );
}



