import Head from "next/head";

export default function Contact() {
    return (
        <>
            <Head>
                <title>Contacts</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="h-screen">
                <h1 className="p-32 text-4xl">Coming Soon</h1>
            </div>
        </>
    );
}



