import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from 'next/head'
import Link from "next/link"
import Image from "next/image"
import { FaBook } from "react-icons/fa"
import { FaCalendarAlt } from "react-icons/fa"
import { RiInboxUnarchiveFill } from "react-icons/ri"
import { AiOutlineHistory } from "react-icons/ai"
import { AiFillDashboard } from "react-icons/ai"
import { MdAccountCircle } from "react-icons/md"
import { MdGroup } from "react-icons/md"
import { GiHelp } from "react-icons/gi"
import SideNav from "../components/SideNav";
import Courses from "../components/Courses";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="relative min-h-screen flex pt-10">
        <aside className="p-10 w-64 space-y-4">
          <h1 className="text-[#193555] text-3xl font-bold">Dashboard</h1>
          <SideNav />
        </aside>

        <blockquote className="flex-1 p-10 text-2xl font-bold bg-[#CBD5E1]">
          <p> content goes here</p>
          <SideNav />
        </blockquote>
      </div>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired();