import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from 'next/head'
import Link from "next/link"
import Image from "next/image"
import { FaBook } from "react-icons/fa"
import { FaCalendarAlt } from "react-icons/fa"
import { RiInboxUnarchiveFill } from "react-icons/ri"
import { AiOutlineHistory } from "react-icons/ai"
import { AiFillDashboard } from "react-icons/ai"
import { MdAccountCircle } from "react-icons/md"
import { MdGroup } from "react-icons/md"
import { GiHelp } from "react-icons/gi"
import SideNav from "../components/SideNav";


export default function Dashboard(){
    return (
        <>
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
  
        <SideNav/>
      </>
    );
}

export const getServerSideProps = withPageAuthRequired();