import Link from "next/link"
import Image from "next/image"
import Head from "next/head";
import { useUser } from '@auth0/nextjs-auth0';
import CourseList from "../components/CourseList";
import MentorList from "../components/MentorList";
import { FaAward } from "react-icons/fa";
import { AiOutlineCalendar } from "react-icons/ai";
import { FaRegHandshake } from "react-icons/fa";
import { AiOutlineClockCircle } from "react-icons/ai";
import { GiSpeaker } from "react-icons/gi";
import { AiOutlineSafetyCertificate } from "react-icons/ai";
import ReactPlayer from 'react-player/lazy';



export default function Designers() {

    //get loggedIn user
    const { user } = useUser();

    return (
        <>
            <Head>
                <title>UI/UX Designers</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            {/* hero section */}
            <div className="pt-24 flex flex-col items-center">
                <h1 className="inline-block px-6 py-2 border-2 border-[#4092CF] text-[#4092CF] font-medium font-bold text-center text-sm leading-tight uppercase rounded-full">PRODUCT DESIGN COURSE</h1>
                <h2 className="text-4xl font-extrabold leading-10 tracking-tight md:text-center sm:leading-none md:text-5xl lg:text-6xl bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-red-400 w-4/6 text-center">Launch your Product Design career in just <br />12 weeks
                </h2>
            </div>

            <header className="h-auto bg-black relative">
                <div className="z-0 absolute inset-0 overflow-hidden pt-[0.6px] z-0">

                    <ReactPlayer
                     controls
                     light="https://res.cloudinary.com/filipe256/image/upload/v1641976469/qraftstore/product_design_pxlkdh.jpg"
                     playing
                     url="https://res.cloudinary.com/filipe256/video/upload/v1643972099/videos/product_design_ltfkbs.mp4"
                     width='100%'
                     height='100%'
                        absolute top-0 left-0 />
                </div>

                <div className="flex flex-col space-y-8">
                    <div className="flex justify-evenly mt-4 w-96 bg-black text-white container mx-auto text-xs">
                        <div className="flex items-center space-x-2">
                            <AiOutlineClockCircle size={20} />
                            <span className="font-bold">12 weeks</span>
                        </div>
                        <div className="flex items-center space-x-2">
                            <GiSpeaker size={20} />
                            <span className="font-bold">English</span>
                        </div>
                        <div className="flex items-center space-x-2">
                            <AiOutlineSafetyCertificate size={20} />
                            <span className="font-bold">Certified Course</span>
                        </div>
                    </div>

                    <div className="pointer-events-auto w-[300px] mt-10 ml-auto mr-12 p-[5px] bg-gradient-to-r from-blue-500 to-red-400 rounded-[15px]">
                        <div className="flex flex-col p-8 space-y-4 bg-white w-72 rounded-[15px]">
                            <h1 className="text-center">The next course starts Early March 2022</h1>
                            <span className="text-center">~5hrs/wk for 12 weeks</span>
                            <Link href="designers/register">
                                <a className="flex self-center justify-center rounded-lg w-36 text-center text-white font-bold text-base p-2 px-4 bg-light-blue hover:bg-blue-400 transition duration-300">Get Started</a>
                            </Link>
                            <p>
                                You don’t need to commit to a four year degree and endless tuition fees to become a Product Designer. Learn your craft and launch your career with Dribbble.
                            </p>
                            <ul className="list-disc">
                                <li>Beginner friendly</li>
                                <li>8 hours on-demand video</li>
                                <li>Weekly 2 hr live sessions</li>
                                <li>Lifetime community access</li>
                            </ul>
                        </div>
                    </div>

                    <div className="opacity-82 bg-black flex justify-evenly w-full container mx-auto text-white pb-10">
                        <div className="w-64 text-center">
                            <AiOutlineCalendar size={20} className="mx-auto" />
                            <h1 className="font-bold mb-4">Flexible learning</h1>
                            <p>No need to quit your job with our mix of video & live learning</p>
                        </div>
                        <div className="w-64 text-center">
                            <FaAward size={20} className="mx-auto" />
                            <h1 className="font-bold mb-4">Mentorship</h1>
                            <p>Weekly live & interactive sessions with your design mentor</p>
                        </div>
                        <div className="w-64 text-center">
                            <FaRegHandshake size={20} className="mx-auto" />
                            <h1 className="font-bold mb-4">Hiring Company Network</h1>
                            <p>Get your portfolio in front of our vast network of top employers</p>
                        </div>
                    </div>
                </div>
            </header>

            {/* content section */}
            <div className="flex flex-col space-y-4 p-8">
                <blockquote className="space-y-2">
                    <h1 className="text-blue-900 font-black text-3xl">UI/UX Designers</h1>
                    <p>&quot; Apprenticeship is a proven model for developing a skilled workforce &quot; <span className="font-black">Eugene Scalia.</span></p>
                    <p>The UX/UI track is a 3 months apprenticeships program offering training and development of individuals looking to <span className="font-black">start a career in product design</span></p>
                    <p className="font-black">Apply</p>
                </blockquote>

                <CourseList />

                <MentorList />

                {!user &&
                    <span className="inline-flex w-full md:w-auto mt-12">
                        <Link href="designers/register"><a className="inline-flex items-center justify-center w-full px-8 py-4 text-base font-bold leading-6 rounded-full md:w-auto bg-[#4092CF] hover:bg-blue-400 transition duration-300">
                            Sign in to apply</a></Link>
                    </span>
                }
                {user &&
                    <span className="inline-flex w-full md:w-auto mt-12">
                        <Link href="designers/register"><a className="inline-flex items-center justify-center w-full px-8 py-4 text-base font-bold leading-6 rounded-full md:w-auto bg-[#4092CF] hover:bg-blue-400 transition duration-300">
                            Apply</a></Link>
                    </span>
                }


            </div>
        </>
    );
}

