import Link from "next/link"
import Image from "next/image"
import Head from "next/head";
import { useUser } from '@auth0/nextjs-auth0';
import CourseList from "../components/CourseList";
import MentorList from "../components/MentorList";

export default function Developers() {

    //get loggedIn user
    const { user } = useUser();

    return (
        <>
            <Head>
                <title>Software Developers</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            {/* hero section */}
            <header className="h-screen">
                <div className=" absolute inset-0 overflow-hidden top-12 ">
                    <Image
                        alt="Background Image"
                        src="https://res.cloudinary.com/filipe256/image/upload/v1642172209/qraftstore/hero-bg_ytthxj.png"
                        layout="fill"
                        objectFit="cover"
                        quality={100}
                    />
                </div>
                <div className="px-4 py-36 text-left text-white md:max-w-none md:text-center z-10 relative">
                    <h1 className="text-4xl font-extrabold leading-10 tracking-tight md:text-center sm:leading-none md:text-6xl lg:text-7xl">
                        <span className="inline-block md:block">Software Developers</span>
                    </h1>

                    <div className="mx-auto mt-5 md:mt-12 md:max-w-xl md:text-center lg:text-lg">
                        Great talent and products are made, not born. Collaborate with
                        industry experts and earn badges that matter, while building
                        products that actually fix the world&#39;s biggest bugs.
                    </div>
                    {!user &&
                        <span className="inline-flex w-full md:w-auto mt-12">
                            <Link href="developer/register"><a className="inline-flex items-center justify-center w-full px-8 py-4 text-base font-bold leading-6 rounded-full md:w-auto bg-[#4092CF] hover:bg-blue-400 transition duration-300">
                                Sign in to apply
                            </a></Link>
                        </span>
                    }
                    {user &&
                        <span className="inline-flex w-full md:w-auto mt-12">
                            <Link href="developer/register"><a className="inline-flex items-center justify-center w-full px-8 py-4 text-base font-bold leading-6 rounded-full md:w-auto bg-[#4092CF] hover:bg-blue-400 transition duration-300">
                                Apply</a></Link>
                        </span>
                    }

                </div>
            </header>

            {/* content section */}
            <div className="flex flex-col space-y-4 p-8">
                <blockquote className="space-y-2">
                    <h1 className="text-blue-900 font-black text-3xl">Software Developers</h1>
                    <p>&quot; Apprenticeship is a proven model for developing a skilled workforce &quot; <span className="font-black">Eugene Scalia.</span></p>
                    <p>The technologist track is a 3 months apprenticeships program offering training and development of individuals looking to <span className="font-black">start a career in technology</span></p>
                    <p className="font-black">Apply</p>
                </blockquote>

                <CourseList />

                <MentorList />

                {!user &&
                    <span className="inline-flex w-full md:w-auto mt-12">
                        <Link href="developer/register"><a className="inline-flex items-center justify-center w-full px-8 py-4 text-base font-bold leading-6 rounded-full md:w-auto bg-[#4092CF] hover:bg-blue-400 transition duration-300">
                            Sign in to apply</a></Link>
                    </span>
                }
                {user &&
                    <span className="inline-flex w-full md:w-auto mt-12">
                        <Link href="developer/register"><a className="inline-flex items-center justify-center w-full px-8 py-4 text-base font-bold leading-6 rounded-full md:w-auto bg-[#4092CF] hover:bg-blue-400 transition duration-300">
                            Apply</a></Link>
                    </span>
                }

            </div>
        </>
    );
}

