import { makePublicRouterInstance } from "next/dist/client/router";
import Head from "next/head";
import Testimonies from "../components/Testimonies";
import Hero from "../components/Hero";
import Courses from "../components/Courses";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Qraft Academy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Hero />
        <Courses />
        <Testimonies/> 
      </div>
    </>
  );
}
