import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from "next/head";
import { useState } from "react";


export default function Register() {

    //radio button show form 
    const [qulification, setQulification] = useState(false);
    const [work, setWork] = useState(false);
    const [training, setTraining] = useState(false);
    const [interview, setInterview] = useState(false);

    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="h-full flex flex-col space-x-4 mt-24 md:container md:mx-auto">
                <h1 className="text-xl md:text-3xl font-black flex justify-center">New? Register to get started</h1>
                <div className="md:grid md:grid-cols-2 w-full border-b-2 border-gray-300 pb-8 mt-8">
                    <div className="flex flex-col max-w-sm space-y-4">
                        <h2 className="text-base md:text-lg font-black">Your Personal Details</h2>

                        <input
                            type="text"
                            className="border rounded-lg required "
                            name="firstname"
                            placeholder="First name" />

                        <input
                            type="text"
                            className="border rounded-lg required "
                            name="lastname"
                            placeholder="Last Name" />

                        <input
                            type="date"
                            className="border rounded-lg required block"
                            name="dob"
                            placeholder="Date of Birth" />

                        <select className=" rounded-lg border required block">
                            <option>Gender</option>
                            <option>M</option>
                            <option>F</option>
                        </select>

                        <input
                            type="number"
                            className="border rounded-lg required  "
                            name="phonenumber"
                            placeholder="Phone Number" />

                        <input
                            type="email"
                            className="border rounded-lg required  "
                            name="email"
                            placeholder="Email" />

                        <input
                            type="password"
                            className="border rounded-lg required  "
                            name="password"
                            placeholder="Password" />

                        <input
                            type="password"
                            className="border rounded-lg required  "
                            name="confirm"
                            placeholder="Confirm Password" />

                    </div>
                    <div className="flex flex-col max-w-sm space-y-4 mt-4 md:mt-0">
                        <h2 className="text-base md:text-lg font-black">Contact Information</h2>

                        <input
                            type="text"
                            className="border rounded-lg required "
                            name="address"
                            placeholder="Address" />

                        <input
                            type="text"
                            className="border rounded-lg required "
                            name="city"
                            placeholder="Town/City" />

                        <input
                            type="text"
                            className="border rounded-lg required "
                            name="country"
                            placeholder="Country" />
                    </div>
                    <button className="bg-[#4092CF] text-white font-bold py-2 mt-4 rounded-lg w-24">Save</button>
                </div >  {/*  -------------------End User details */}


                <div className="flex flex-col mt-8 border-b-2 border-gray-300 pb-4">
                    <h2 className="text-base md:text-lg font-black mb-4">Education</h2>
                    <label className="flex flex-col">
                        <span className="text-sm font-bold">Name of most recent school or college?</span>
                        <input
                            type="text"
                            className="border rounded-lg required  max-w-sm"
                            name="address" />
                    </label>
                    <div className="flex space-x-4 mt-2">
                        <label>
                            <span className="block font-bold">Started</span>
                            <input
                                type="number"
                                className="border rounded-lg required w-24"
                                name="started" />
                        </label>
                        <label className="">
                            <span className="block font-bold">Finished</span>
                            <input
                                type="number"
                                className="border rounded-lg required w-24"
                                name="finished" />
                        </label>

                    </div>
                    <button className="bg-[#4092CF] text-white font-bold py-2 mt-4 rounded-lg w-24">Save</button>
                </div>{/* -------------------End Education */}


                <div className="md:flex flex-col border-b-2 border-gray-300">
                    <div className="flex flex-col mt-8 mb-4">
                        <h2 className="text-base md:text-lg font-black">Qualifications</h2>
                        <span className="text-sm font-bold">Do you have any qualifications?</span>
                        <div className="flex space-x-10 pt-4">
                            <label className="flex space-x-4 items-center" onClick={() => setQulification(true)}>
                                <span>Yes</span>
                                <input
                                    type="radio"
                                    className="form-radio text-[#4092CF] w-8 h-8"
                                    name="radio1"
                                    checked={qulification == true}
                                />
                            </label>

                            <label className="flex space-x-4 items-center" onClick={() => setQulification(false)}>
                                <span>No</span>
                                <input
                                    type="radio"
                                    className="form-radio text-[#4092CF] w-8 h-8"
                                    name="radio1"
                                    checked={qulification == false}
                                />
                            </label>
                        </div>
                        {qulification &&
                            <div className="space-y-4 mt-8 max-w-sm">
                                <label className="flex flex-col">
                                    <span className="text-base font-bold">Type of qualifications</span>
                                    <select className=" rounded-lg border required block">
                                        <option>Level</option>
                                        <option>Certificate</option>
                                        <option>Diploma</option>
                                        <option>Degree</option>
                                    </select>
                                </label>
                                <label className="flex flex-col">
                                    <span className="font-bold">Year</span>
                                    <input
                                        type="number"
                                        className="border rounded-lg required w-24"
                                        name="yesr" />
                                </label>

                                <label className="flex flex-col">
                                    <span className="font-bold">Subject</span>
                                    <input
                                        type="text"
                                        className="border rounded-lg required "
                                        name="subject" />
                                </label>

                                <label className="flex flex-col">
                                    <span className="font-bold">Grade</span>
                                    <input
                                        type="text"
                                        className="border rounded-lg required "
                                        name="grade" />
                                </label>
                                <button className="bg-[#4092CF] text-white font-bold py-2 mt-4 rounded-lg w-24">Save</button>
                            </div>
                        }
                    </div>
                </div>{/* End Qualifications */}

                <div className="md:flex flex-col border-b-2 border-gray-300">
                    <div className="flex flex-col mt-8 mb-4">
                        <h2 className="text-base md:text-lg font-black">Work Experience</h2>
                        <span className="text-sm font-bold">Do you have any work experience?</span>
                        <div className="flex space-x-10 pt-4">
                            <label className="flex space-x-4 items-center" onClick={() => setWork(true)}>
                                <span>Yes</span>
                                <input
                                    type="radio"
                                    className="form-radio text-[#4092CF] w-8 h-8"
                                    name="radio2"
                                    checked={work == true} />
                            </label>

                            <label className="flex space-x-4 items-center" onClick={() => setWork(false)}>
                                <span>No</span>
                                <input
                                    type="radio"
                                    className="form-radio text-[#4092CF] w-8 h-8"
                                    name="radio2"
                                    checked={work == false} />
                            </label>
                        </div>
                        {work &&
                            <div className="space-y-4 mt-8 max-w-sm">
                                <label className="flex flex-col">
                                    <span className="font-bold">Employer</span>
                                    <input
                                        type="text"
                                        className="border rounded-lg required "
                                        name="employer" />
                                </label>

                                <label className="flex flex-col">
                                    <span className="font-bold">Job Title</span>
                                    <input
                                        type="text"
                                        className="border rounded-lg required "
                                        name="jobtitle" />
                                </label>
                                <label className="flex flex-col">
                                    <span className="font-bold">Main Duties</span>
                                    <textarea className="resize border rounded-md"></textarea>
                                </label>
                                <div className="flex flex-col md:flex-row md:space-x-8 space-y-2 md:space-y-0">
                                    <div>
                                        <label className="block font-bold">Started</label>
                                        <div className="inline-flex md:flex space-x-8 md:space-x-4">
                                            <div className="">
                                                <span className="text-gray-400 block">Month</span>
                                                <select className="rounded-lg border required md:mr-2">
                                                    <option>Jan</option>
                                                    <option>Feb</option>
                                                    <option>Mar</option>
                                                    <option>Apr</option>
                                                </select>
                                            </div>
                                            <div>
                                                <span className="text-gray-400 block">Year</span>
                                                <input
                                                    type="number"
                                                    className="border rounded-lg required w-24"
                                                    name="year" />
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <label className="block font-bold">Finished</label>
                                        <div className="inline-flex md:flex space-x-8 md:space-x-4">
                                            <div className="">
                                                <span className="text-gray-400 block">Month</span>
                                                <select className="rounded-lg border required md:mr-2">
                                                    <option>Jan</option>
                                                    <option>Feb</option>
                                                    <option>Mar</option>
                                                    <option>Apr</option>
                                                </select>
                                            </div>
                                            <div>
                                                <span className="text-gray-400 block">Year</span>
                                                <input
                                                    type="number"
                                                    className="border rounded-lg required w-24"
                                                    name="year" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <button className="bg-[#4092CF] text-white font-bold py-2 mt-4 rounded-lg w-24">Save</button>
                            </div>
                        }
                    </div>
                </div>{/* End Work Experience */}

                <div className="md:flex flex-col border-b-2 border-gray-300">
                    <div className="flex flex-col mt-8 mb-4">
                        <h2 className="text-base md:text-lg font-black">Traning Courses</h2>
                        <span className="text-sm font-bold">Have you been on a training course?</span>
                        <div className="flex space-x-10 pt-4">
                            <label className="flex space-x-4 items-center" onClick={() => setTraining(true)}>
                                <span>Yes</span>
                                <input
                                    type="radio"
                                    className="form-radio text-[#4092CF] w-8 h-8"
                                    name="radio3"
                                    checked={training == true} />
                            </label>

                            <label className="flex space-x-4 items-center" onClick={() => setTraining(false)}>
                                <span>No</span>
                                <input
                                    type="radio"
                                    className="form-radio text-[#4092CF] w-8 h-8"
                                    name="radio3"
                                    checked={training == false} />
                            </label>
                        </div>
                        {training &&
                            <div className="space-y-4 mt-8 max-w-sm">
                                <label className="flex flex-col">
                                    <span className="font-bold">Provider</span>
                                    <input
                                        type="text"
                                        className="border rounded-lg required "
                                        name="provider" />
                                </label>

                                <label className="flex flex-col">
                                    <span className="font-bold">Course title</span>
                                    <input
                                        type="text"
                                        className="border rounded-lg required "
                                        name="Course" />
                                </label>
                                <div className="flex flex-col md:flex-row md:space-x-8 space-y-2 md:space-y-0">
                                    <div>
                                        <label className="block font-bold">From</label>
                                        <div className="inline-flex md:flex space-x-8 md:space-x-4">
                                            <div className="">
                                                <span className="text-gray-400 block">Month</span>
                                                <select className="rounded-lg border required md:mr-2">
                                                    <option>Jan</option>
                                                    <option>Feb</option>
                                                    <option>Mar</option>
                                                    <option>Apr</option>
                                                </select>
                                            </div>
                                            <div>
                                                <span className="text-gray-400 block">Year</span>
                                                <input
                                                    type="number"
                                                    className="border rounded-lg required w-24"
                                                    name="year" />
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <label className="block font-bold">To</label>
                                        <div className="inline-flex md:flex space-x-8 md:space-x-4">
                                            <div className="">
                                                <span className="text-gray-400 block">Month</span>
                                                <select className="rounded-lg border required md:mr-2">
                                                    <option>Jan</option>
                                                    <option>Feb</option>
                                                    <option>Mar</option>
                                                    <option>Apr</option>
                                                </select>
                                            </div>
                                            <div>
                                                <span className="text-gray-400 block">Year</span>
                                                <input
                                                    type="number"
                                                    className="border rounded-lg required w-24"
                                                    name="year" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <button className="bg-[#4092CF] text-white font-bold py-2 mt-4 rounded-lg w-24">Save</button>
                            </div>
                        }
                    </div>
                </div>{/* End Traning Courses */}

                <div className="md:flex flex-col max-w-sm mt-8 mb-4">
                    <div className="space-y-4">
                        <h2 className="text-base md:text-lg font-black mb-8">About You</h2>
                        <label className="flex flex-col">
                            <p className="text-sm font-bold">What are your main strengths?</p>
                            <span className="text-sm text-gray-400">Please provide examples of when you&#39;ve demostrated your strengths</span>
                            <textarea className="resize border rounded-md"></textarea>
                            <span className="text-sm text-gray-400">4000 characters remaining</span>
                        </label>
                        <label className="flex flex-col">
                            <p className="text-sm font-bold">What skills would you like to improve during this apprenticeship?</p>
                            <span className="text-sm text-gray-400">Think of what your main duties would be and whether there are skills you&#39;d like to develop</span>
                            <textarea className="resize border rounded-md"></textarea>
                            <span className="text-sm text-gray-400">4000 characters remaining</span>
                        </label>
                        <label className="flex flex-col">
                            <p className="text-sm font-bold">What are your hobbies and interests?</p>
                            <span className="text-sm text-gray-400">Remember to include any personal achievements</span>
                            <textarea className="resize border rounded-md"></textarea>
                            <span className="text-sm text-gray-400">4000 characters remaining</span>
                        </label>

                        <h2 className="text-base md:text-lg font-black">Additional Questions</h2>
                        <label className="flex flex-col">
                            <p className="text-sm font-bold">What attracted you to the vacancy?</p>
                            <textarea className="resize border rounded-md"></textarea>
                            <span className="text-sm text-gray-400">4000 characters remaining</span>
                        </label>
                        <label className="flex flex-col">
                            <p className="text-sm font-bold">What skills could you bring to the role?</p>
                            <textarea className="resize border rounded-md"></textarea>
                            <span className="text-sm text-gray-400">4000 characters remaining</span>
                        </label>
                        <label className="flex flex-col">
                            <p className="text-sm font-bold">Is there anything we can do to support your inverview?</p>
                            <div className="flex space-x-10 pt-4 mb-4">
                                <label className="flex space-x-4 items-center" onClick={() => setInterview(true)}>
                                    <span>Yes</span>
                                    <input
                                        type="radio"
                                        className="form-radio text-[#4092CF] w-8 h-8"
                                        name="radio4"
                                        checked={interview == true} />
                                </label>

                                <label className="flex space-x-4 items-center" onClick={() => setInterview(false)}>
                                    <span>No</span>
                                    <input
                                        type="radio"
                                        className="form-radio text-[#4092CF] w-8 h-8"
                                        name="radio4"
                                        checked={interview == false} />
                                </label>
                            </div>
                            {interview &&
                                <>
                                    <p className="text-sm font-bold">Provide details of interview support</p>
                                    <textarea className="resize border rounded-md"></textarea>
                                    <span className="text-sm text-gray-400">4000 characters remaining</span>
                                </>
                            }
                        </label>
                        <button className="bg-[#4092CF] text-white font-bold py-2 rounded-lg w-40">Save and Continue</button>
                    </div>
                </div>{/* End About you */}

            </div>
        </>
    );
}


export const getServerSideProps = withPageAuthRequired();