import Head from "next/head";

const Tracks = () => {
    return (
        <>
        <Head>
        <title>Trucks</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
        <div className="h-screen">
         <h1 className="p-32 text-4xl">Coming Soon</h1>
        </div>
        </>
    );
}

export default Tracks;

