import Link from "next/link"
import Image from "next/image"
import Head from "next/head";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

export default function Register() {

    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="h-auto">
               
                    <iframe
                        src="https://docs.google.com/forms/d/e/1FAIpQLSfajmDMnB22QoB-jdwNFeHiHwuPZOmOAiygTo8trKbEkpZAGA/viewform"
                        width="100%" height="3000" frameBorder="0" marginHeight="0" marginWidth="0" 
                        className="mt-24">
                        Loading…
                    </iframe>
                </div>
        
        </>
    );
}
